export default {
  SET_COURSES: 'SET_COURSES',
  SET_SUBJECTS: 'SET_SUBJECTS',
  SET_SEMESTERS: 'SET_SEMESTERS',
  SET_SECTIONS: 'SET_SECTIONS',
  SET_SPECIALIZATIONS: 'SET_SPECIALIZATIONS',
  SET_STUDENTS: 'SET_STUDENTS'
};
