export default {
  SET_DASHBOARD_DATA: 'SET_DASHBOARD_DATA',

  SET_NOTICES_AND_CIRCULARS: 'SET_NOTICES_AND_CIRCULARS',
  SET_ACADEMIC_DETAILS: 'SET_ACADEMIC_DETAILS',
  SET_INSTITUTE_DETAILS: 'SET_INSTITUTE_DETAILS',
  USER_LOGOUT: 'USER_LOGOUT',
  SET_FACULTY_DASHBOARD_DATA: 'SET_FACULTY_DASHBOARD_DATA',
  SET_FACULTY_DASHBOARD_DATA_NAV: 'SET_FACULTY_DASHBOARD_DATA_NAV',
  SET_NOTIFICATIONS: 'SET_NOTIFICATIONS',
  CLEAR_NOTIFICATIONS_COUNT: 'CLEAR_NOTIFICATIONS_COUNT',
};
