export default {
  BASE_URL: 'http://182.18.162.129:105/Calender_details.asmx/',
  INSTITUTE_BASE_URL: 'http://182.18.162.129:91/Calender_details.asmx/',
  appName: 'ESIM Campus Solution',
  routeNames: {
    CONSENT_FORM: 'consentForm',
    CHANGE_PASSWORD: 'changePassword',
    STUDENT_MARKSHEET_DETAILS: 'studentMarkSheetDetails',
    COURSE_REGISTRATION: 'courseRegistration',
    GATE_PASS_REQUEST: 'gatePassRequest',
    FEE_PAY: 'feePay',
    ADMIT_CARD: 'admitCard',
    FEE_DETAIL: 'feeDetail',
    PAYMENT_FORM: 'paymentForm',
    ATTENDANCE_SUBJECT_WISE: 'attendanceSubjectWise',
    CONDENSED_FORM_FEE: 'condensedFormFee',
    FACULTY_PROFILE: 'facultyProfile',
    STUDENT_ATTENDANCE: 'studentAttendance',
    ADD_STUDENT_ATTENDANCE: 'addStudentAttendance',
    BACK_PAPER_FORM: 'backPaperForm',
    TRANSPORT_CARD:'transportcard',
    HOSTEL_CARD:'hostelcard',
    Faculty_CARD: 'Facultycard',
    Attendance_VIEW : 'AttendanceView',
    Webview:'webview',
    NOTIFICATIONS: 'notifications',
    HOSTEL_LEAVE: 'hostelLeave',
    ADD_HOSTEL_LEAVE: 'addHostelLeave',
    DAY_OUT: 'dayOut',
    ADD_DAY_OUT: 'addDayOut',
    FEE_SETUP: 'feeSetup',
  },
  
  courseRegistration: {
    inputLabels: {
      RegNo: 'Admission No./Enrollment No.',
      AadharNo: 'Aadhar No.',
      StudentName: "Student Name (In Block Letter's)",
      StudentName_IN_Hindi: 'Student Name (In Hindi)',
      FatherName: "Father's Name",
      FatherContactNo: "Father's Contact No",
      MotherName: "Mother's Name",
      MotherContactNo: "Mother's Contact No",
      ParentEmailID: "Parent's Email ID",
      Religion: 'Religion',
      ParentContactNo: "Parent's Contact No.",
      Caste: 'Caste',
      Category: 'Category',
      Gender: 'Gender',
      Nationality: 'Nationality',
      Country: 'Country',
      MobileNo: 'Mobile No.',
      WhatsappNo: 'Whatsapp No.',
      EmailID: 'E-mail ID',
      FacebookID: 'Facebook ID',
      Semester: 'Semester',
      Session: 'Session',
      SchoolName: 'School',
      CourseName: 'Course Name',
      Specilisation: 'Specialisation',
      CurrentAddress: 'Current Address',
      CurrentDistrict: 'Current District',
    },
  },
};
