export default {
  SET_BACK_PAPER_EXAM_NAME: 'SET_BACK_PAPER_EXAM_NAME',
  SET_BACK_PAPER_SEMESTERS: 'SET_BACK_PAPER_SEMESTERS',
  SET_BACK_PAPER_GRADES: 'SET_BACK_PAPER_GRADES',
  SET_BACK_PAPER_SUBJECTS: 'SET_BACK_PAPER_SUBJECTS',
  SET_BACK_PAPER_AMOUNT: 'SET_BACK_PAPER_AMOUNT',
};
