export default {
  SET_FEE_DUE_DETAIL: 'SET_FEE_DUE_DETAIL',
  SET_VOUCHER_DETAIL: 'SET_VOUCHER_DETAIL',
  SET_RECEIPT_DETAIL: 'SET_RECEIPT_DETAIL',
  SET_PREV_TRANSACTION_DETAIL: 'SET_PREV_TRANSACTION_DETAIL',
  SET_POST_PAYMENT_RESPONSE: 'SET_POST_PAYMENT_RESPONSE',
  SET_STUDENT_FEE_HEAD_VOUCHAR_DETAIL: 'SET_STUDENT_FEE_HEAD_VOUCHAR_DETAIL',
};
